### ISSUE TITLE
Regional blks can't be unpacked

### ISSUE THREAD

**Issue by gszabi99** [kotiq/blk#1]
Trying to unpack blks from regional.vromfs.bin_u fails with the following error message:
![image](https://user-images.githubusercontent.com/45767091/128057680-53873568-cb62-451f-a059-876d653ddd10.png)
Could this be somehow fixed perhaps?

EDIT: I've just now seen how the namemap of regional is apparently unreadable. Quite unfortunate.

**Comment by kotiq** [comment]
I found this file in cache/binary.2.7.0
The file has the signature `b'VRFs'`. 
According to the logic of the file system unpacker, the `is_new_version` flag is determined by the version number located in the header extension `ext_header`.
But only a file with the `b'VFRx'` signature has this extension.
Therefore, the value of the new version flag remains `False`. And I see the Zstandard signature `bytes.fromhex('28B52FFD')` in the files. 

Temporarily activate the flag for this archive in `wt_tools/formats/vromfs_parser.py:189`
I will have to find a way to correctly set the flag for archives with the signature `b'VRFs'`

I have changed the logic of processing subdirectories of the directory with the `nm` file in `blk_unpack_demo.py`. Please update the `blk`.

**Comment by kotiq** [comment]
[0001-vromfs_unpacker-fix-new-version-flag-for-vrfs-magic.zip](https://github.com/kotiq/blk/files/6929960/0001-vromfs_unpacker-fix-new-version-flag-for-vrfs-magic.zip)
I made a correction for the flag in `wt_tools/vromfs_unpacker.py`. Now the version is considered new if there are compressed files inside the file system.

**Comment by kotiq** [comment]
[patches.zip](https://github.com/kotiq/blk/files/6930354/patches.zip)
I made a correction for the flag in wt_tools/vromfs_unpacker.py. 
Now the version is considered new if there are compressed files inside the file system and files with package type 2 are extracted from the archive.

**Comment by gszabi99** [comment]
Thank you, it works!
