### ISSUE TITLE
Альтернативный вариант формата JSON

### ISSUE THREAD

**Issue by Viz-Allati** [kotiq/blk#3]
Предлагаю сделать новый вариант сериализации в JSON как нечто среднее между имеющимися json и json_2, думаю показать на примере будет проще.
Текущий формат json:
```
  "pv_sturmbot39": [
    {
      "_extends": "civil_boat"
    },
    {
      "_extends": "four_seats_vehicle"
    },
    {
      "animchar.res": "pv_sturmbot39_char"
    },
    {
      "collres.res": "pv_sturmbot39_collision"
    },
    {
      "ship_net_phys.blk": "gamedata/units/ships/pv_sturmbot39.blk:ShipPhys"
    }
  ],
```
Текущий формат json_2:
```
  "pv_sturmbot39": [
    {
      "_extends": [
        "civil_boat",
        "four_seats_vehicle"
      ],
      "animchar.res": [
        "pv_sturmbot39_char"
      ],
      "collres.res": [
        "pv_sturmbot39_collision"
      ],
      "ship_net_phys.blk": [
        "gamedata/units/ships/pv_sturmbot39.blk:ShipPhys"
      ]
    }
  ],
```
Предлагаемый вариант:
```
  "pv_sturmbot39": {
    "_extends": [
      "civil_boat",
      "four_seats_vehicle"
    ],
    "animchar.res": "pv_sturmbot39_char",
    "collres.res": "pv_sturmbot39_collision",
    "ship_net_phys.blk": "gamedata/units/ships/pv_sturmbot39.blk:ShipPhys"
  }
```
Т.е. значения с одинаковыми ключами собираются в массив, а одиночные остаются простой парой ключ-значение.

Python-программист из меня так себе, поэтому пример кода корявенький и скорее всего не во всем ситуациях отрабатывает корректно:
```
class JSONMapper(Mapper):
    @classmethod
    def _map_section(cls, section: Section) -> t.Union[t.Sequence, t.Mapping]:
        items = section.items()
        if not items:
            return []
        else:
            m: t.Union[list, dict] = {}
            for n, vs in items:
                if len(vs) == 1:
                    v = vs[0]
                    if isinstance(m, list):
                        m.append({n: cls._map_value(v)})
                    else:
                        m[n] = cls._map_value(v)
                else:
                    if not isinstance(m, list):
                        m = [{n: v} for n, v in m.items()]
                    for v in vs:
                        if n in m:
                            if isinstance(m[n], list):
                                m[n].append(cls._map_value(v))
                            else:
                                m[n] = [m[n]]
                                m[n].append(cls._map_value(v))
                        else:
                            if not isinstance(m, dict): m = {}
                            m.update({n: cls._map_value(v)})
            return m
```
В теории можно сделать отдельным форматом а-ля json_3, но насколько я понял там идет связь с оригинальным blk_unpack'ом из wt-tools, что несколько затрудняет такое развитие событий.

**Comment by kotiq** [comment]
У меня есть парсер 3-й версии blk на construct старой версии, написанный пару лет назад. Так что, от оригинального wt-tools можно отвязаться в этом пакете. К тому же, двоичные файлы 3-й версии мне попадались редко среди файлов WarThunder. Для 2-й версии упаковки blk у меня нет образцов, чтобы проверить корректность распаковки.

Вы собираетесь импортировать `json_3` куда-то? Как-то наткнулся на импорт json при построении интерактивного дерева исследования по `char/config/shop.blk` и выбрал вариант `имя -> массив` из самой секции, что эквивалентно `json_2`. Для `cerberus`-подобной библиотеки мне было проще составить схему валидации-нормализации. Для варианта `json_1` я даже не пытался.

**Comment by Viz-Allati** [comment]
У меня самопальные скрипты на php, которые из кучки .blk-файлов (Enlisted\CRSED) собирают сущности и кое-как пытаются пройти по иерархии наследования, чтобы в итоге конечные значения получить. От темы полноценного парсинга с лексерами и прочим разбором я несколько далёк, поэтому прибегаю к использованию json. Вышеобозначенный формат был бы лично мне просто удобнее. Если есть какие-то принципиальные проблемы с таким выводом или слишком сложно сделать его правильно, то не проблема, буду переделывать имеющиеся форматы на своей стороне.

**Comment by kotiq** [comment]
Да не проблема. Как пустую секцию представлять: пустим массивом или пустым объектом? В предыдущих форматах был пустой массив. Стандартная библиотека дает для пустого словаря пустой объект.

**Comment by Viz-Allati** [comment]
Как будет удобнее реализовывать, для моих целей особой разницы не будет что так, что сяк.
> Для 2-й версии упаковки blk у меня нет образцов, чтобы проверить корректность распаковки.

Кстати, под версией 2 я так понимаю подразумеваются файлы до недавней смены формата? У меня есть неполная коллекция .vromfs.bin из CRSED начиная где-то с 2018 года, если что-то из этого нужно - буду рад предоставить.

**Comment by kotiq** [comment]
2-я версия начинается с байтов `00424246 0200`, до WarThunder 1.45.
3-я версия начинается с байтов `00424246 0300`, с WarThunder 1.47.

**Comment by kotiq** [comment]
@Viz-Allati добавил сжатием мультизначения для длины 1. Вроде, похоже для `char/config/shop.blk`. Не делал оформление, чтобы массив располагался в одной строке.

**Comment by Viz-Allati** [comment]
Отлично, то что надо, спасибо. Только с некоторыми файлами затык происходит:
> D:\Soft\DataMining>blk-master\tests\demo\blk_unpack_demo.py mexico-content.vromfs.bin_u --format=json_3
mexico-content.vromfs.bin_u\levels\mexico_4x4.blk
error out type: 4

json и json_2 на нём отрабатывают нормально. Что самое интересное, есть практически идентичный mexico_4x4.blk в другом .vromfs.bin файле, там всё хорошо. Видимо в формате какие-то различия.

Прикладываю проблемный файл [mexico.zip](https://github.com/kotiq/blk/files/7078497/mexico.zip)

**Comment by kotiq** [comment]
Это файл прежнего формата, для него секция не строится. Надо будет дописывать построение секции по нему.

**Comment by kotiq** [comment]
Само преобразование из `json_2` в `json_3` простое, достаточно синглтоны превратить в лежащие в них значения. Как временное решение [json2_to_json3.py](https://gist.github.com/kotiq/4d1ff4fc3ba292cfc5d3d182b786db7a#file-json2_to_json3-py)
Результат 
```
cat /tmp/json3/mexico_4x4.blkx | python json2_to_json3.py | python -m json.tool > mexico_4x4.json
```
[mexico_4x4.zip](https://github.com/kotiq/blk/files/7079117/mexico_4x4.zip)

**Comment by kotiq** [comment]
Добавил `json_3` в `blk_unpack`.
https://github.com/kotiq/wt-tools/commit/0a4b7f8918adf6291320deb89fac0ef21c85ec6c

**Comment by Viz-Allati** [comment]
Всё работает. Ещё раз спасибо.
