### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by OshidaBCF** [kotiq/blk#5]
Could it be possible to have an English version of the docs

I'm trying to learn how all the tools i use works, but i don't know a word of russian.

**Comment by kotiq** [comment]
I'm not that good at English. The translator from yandex and deepl give good results.

**Comment by OshidaBCF** [comment]
For text yes, but the images aren't translatable, or is there some "text" file somewhere that get converted to an image ?

**Comment by kotiq** [comment]
Yandex image translation does the job. I use it when I get chat messages in Far Eastern languages.

**Comment by OshidaBCF** [comment]
I see, well the doc is very useful so thanks for making it in the first place
